steps:
  - label: "Push Papertrail release images to ECR"
    branches: "main"
    command:
      - make image
      - make tags
      - make push
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: arn:aws:iam::009999273940:role/fluentd-kubernetes-daemonset-deploy
      - ecr#v2.3.0:
          login: true
          region: "us-west-2"
      - docker#v3.8.0:
          image: cimg/base:stable
          user: root
          environment:
            - "DOCKERFILE=v1.12/debian-papertrail"
          volumes:
            - "${HOME}/.docker:/root/.docker:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
    timeout_in_minutes: 15
