#!/bin/bash

set -euo pipefail

###+ Configuration
DOCKER_IMAGE_NAME="009999273940.dkr.ecr.us-west-2.amazonaws.com/democracyworks/fluentd-kubernetes-daemonset"
###-

latest_image="${DOCKER_IMAGE_NAME}:v1.12-debian-papertrail-latest"

docker build --pull -t "${latest_image}" \
  docker-image/v1.12/debian-papertrail

docker tag ${latest_image} \
  ${DOCKER_IMAGE_NAME}:v1.12.1-debian-papertrail-1.0
docker tag ${latest_image} \
  ${DOCKER_IMAGE_NAME}:v1.12-debian-papertrail-1

docker push ${DOCKER_IMAGE_NAME}:v1.12.1-debian-papertrail-1.0
docker push ${DOCKER_IMAGE_NAME}:v1.12-debian-papertrail-1
